Remove starting Crossvec from SCP-035 on spawn
redsunservers/SCP-Secret-Fortress pull request #84
Opened 2022-07-21 18:39 UTC by Darkita162

Seriously, whos idea was this to give him the best weapon in the game to start of with?

2022-07-27 16:09 UTC, Mikusch requested changes
The Crossvec for SCP-035 is also defined in map config files, please go through them all to make sure you're not missing one.

2022-07-27 16:09 UTC, Mikusch commented on addons/sourcemod/configs/scp_sf/classes.cfg
> +			"1"	"30758"	// Prinny Machete #This guy shouldn't spawn with a gun right at the start. If he can find a gun, good for him, just don't give him one of the best in the mode to fuck people over with.
Please leave your opinion out of code comments.
```suggestion
			"1"	"30758"	// Prinny Machete
```

2022-07-27 16:09 UTC, Mikusch commented on addons/sourcemod/configs/scp_sf/classes.cfg
> +
Try not to change the indentation/whitespace of the file.

2022-07-28 21:53 UTC, FortyTwoFortyTwo commented
`scp_turtle_support.cfg` map config also needs to be updated as it have scp035 with Crossvec

2022-08-04 08:52 UTC, closed without merging